name: hoox
channels:
  - conda-forge
  - bioconda
dependencies:
  # Snakefile
  - snakemake
  - fd-find
  - ncbi-datasets-cli
  - r-base
  - r-tidyverse
  - r-data.table
  - unzip
  - biopython
  - r-seqinr
  - r-furrr
  - pyhmmer=0.10.14
  # install_iscan.py  
  - httplib2
  - aria2
  - openjdk
  # install_Rlibs.R
  - zlib
  # Makefile
  - black
  - isort
  - snakefmt
  - r-styler
  - parallel
  - imagemagick
  # Development
  - ipython
